export type StudentApplication = {
  id: string;
  name: string;
  enrollment: string;
  roomType: string;
  quota: string;
  year: string;
  suggestedBed: string;
  status: "Pending" | "Approved" | "Rejected" | "Waitlist";
};

export const studentApplication: StudentApplication[] = [
  { id: "1", name: "Aarav Sharma", enrollment: "2025A001", roomType: "Single", quota: "General", year: "1st", suggestedBed: "Room 101", status: "Pending" },
  { id: "2", name: "Priya Verma", enrollment: "2025B012", roomType: "Double", quota: "OBC", year: "2nd", suggestedBed: "Room 203", status: "Pending" },
  { id: "3", name: "Rohan Gupta", enrollment: "2025C003", roomType: "Single", quota: "SC", year: "1st", suggestedBed: "Room 105", status: "Approved" },
  { id: "4", name: "Ananya Singh", enrollment: "2025D004", roomType: "Double", quota: "General", year: "2nd", suggestedBed: "Room 210", status: "Rejected" },
  { id: "5", name: "Ishaan Mehta", enrollment: "2025E005", roomType: "Single", quota: "OBC", year: "3rd", suggestedBed: "Room 112", status: "Waitlist" },
  { id: "6", name: "Sanya Kapoor", enrollment: "2025F006", roomType: "Double", quota: "SC", year: "1st", suggestedBed: "Room 215", status: "Pending" },
  { id: "7", name: "Vivaan Reddy", enrollment: "2025G007", roomType: "Single", quota: "General", year: "2nd", suggestedBed: "Room 120", status: "Approved" },
  { id: "8", name: "Tanya Nair", enrollment: "2025H008", roomType: "Double", quota: "OBC", year: "3rd", suggestedBed: "Room 220", status: "Rejected" },
  { id: "9", name: "Kabir Joshi", enrollment: "2025I009", roomType: "Single", quota: "SC", year: "1st", suggestedBed: "Room 125", status: "Pending" },
  { id: "10", name: "Anika Choudhary", enrollment: "2025J010", roomType: "Double", quota: "General", year: "2nd", suggestedBed: "Room 225", status: "Approved" },
  { id: "11", name: "Devanshi Saxena", enrollment: "2025K011", roomType: "Single", quota: "OBC", year: "3rd", suggestedBed: "Room 130", status: "Waitlist" },
  { id: "12", name: "Arjun Mishra", enrollment: "2025L012", roomType: "Double", quota: "SC", year: "1st", suggestedBed: "Room 230", status: "Pending" },
  { id: "13", name: "Riya Bhatia", enrollment: "2025M013", roomType: "Single", quota: "General", year: "2nd", suggestedBed: "Room 135", status: "Approved" },
  { id: "14", name: "Shaurya Jain", enrollment: "2025N014", roomType: "Double", quota: "OBC", year: "3rd", suggestedBed: "Room 235", status: "Rejected" },
  { id: "15", name: "Anshika Pandey", enrollment: "2025O015", roomType: "Single", quota: "SC", year: "1st", suggestedBed: "Room 140", status: "Pending" },
  { id: "16", name: "Karan Thakur", enrollment: "2025P016", roomType: "Double", quota: "General", year: "2nd", suggestedBed: "Room 240", status: "Approved" },
  { id: "17", name: "Sakshi Raina", enrollment: "2025Q017", roomType: "Single", quota: "OBC", year: "3rd", suggestedBed: "Room 145", status: "Waitlist" },
  { id: "18", name: "Aditya Kulkarni", enrollment: "2025R018", roomType: "Double", quota: "SC", year: "1st", suggestedBed: "Room 245", status: "Pending" },
  { id: "19", name: "Meera Sharma", enrollment: "2025S019", roomType: "Single", quota: "General", year: "2nd", suggestedBed: "Room 150", status: "Approved" },
  { id: "20", name: "Raghav Bansal", enrollment: "2025T020", roomType: "Double", quota: "OBC", year: "3rd", suggestedBed: "Room 250", status: "Rejected" },
  { id: "21", name: "Tanvi Joshi", enrollment: "2025U021", roomType: "Single", quota: "SC", year: "1st", suggestedBed: "Room 155", status: "Pending" },
  { id: "22", name: "Vedant Desai", enrollment: "2025V022", roomType: "Double", quota: "General", year: "2nd", suggestedBed: "Room 255", status: "Approved" },
  { id: "23", name: "Aisha Iyer", enrollment: "2025W023", roomType: "Single", quota: "OBC", year: "3rd", suggestedBed: "Room 160", status: "Waitlist" },
  { id: "24", name: "Ishita Chatterjee", enrollment: "2025X024", roomType: "Double", quota: "SC", year: "1st", suggestedBed: "Room 260", status: "Pending" },
  { id: "25", name: "Reyansh Singh", enrollment: "2025Y025", roomType: "Single", quota: "General", year: "2nd", suggestedBed: "Room 165", status: "Approved" },
  { id: "26", name: "Nivedita Rao", enrollment: "2025Z026", roomType: "Double", quota: "OBC", year: "3rd", suggestedBed: "Room 265", status: "Rejected" },
  { id: "27", name: "Devika Kapoor", enrollment: "2026A027", roomType: "Single", quota: "SC", year: "1st", suggestedBed: "Room 170", status: "Pending" },
  { id: "28", name: "Aryan Malhotra", enrollment: "2026B028", roomType: "Double", quota: "General", year: "2nd", suggestedBed: "Room 270", status: "Approved" },
  { id: "29", name: "Prisha Yadav", enrollment: "2026C029", roomType: "Single", quota: "OBC", year: "3rd", suggestedBed: "Room 175", status: "Waitlist" },
  { id: "30", name: "Ritvik Nair", enrollment: "2026D030", roomType: "Double", quota: "SC", year: "1st", suggestedBed: "Room 275", status: "Pending" },
];

export type HostelComplaint = {
  id: number;
  studentName: string;
  room: string;
  category: string;
  description: string;
  dateRaised: string;
  assignedStaff: string;
  status: string;
  notes: string;
}

export const hostelComplaints: HostelComplaint[] = [
  {
    id: 1,
    studentName: "Aarav Sharma",
    room: "A-101",
    category: "Plumbing",
    description: "Leaking tap in the bathroom causing water to spill on the floor.",
    dateRaised: "2025-09-20",
    assignedStaff: "Ramesh Kumar",
    status: "Pending",
    notes: "",
  },
  {
    id: 2,
    studentName: "Sanya Mehta",
    room: "B-205",
    category: "Electricity",
    description: "Light bulb not working and frequent power cuts in the room.",
    dateRaised: "2025-09-21",
    assignedStaff: "Unassigned",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 3,
    studentName: "Rahul Verma",
    room: "C-302",
    category: "Cleaning",
    description:
      "The washroom is dirty and not cleaned properly for the past 3 days.",
    dateRaised: "2025-09-19",
    assignedStaff: "Sunita Joshi",
    status: "Resolved",
    notes: "Cleaning done on 2025-09-22",
  },
  {
    id: 4,
    studentName: "Priya Singh",
    room: "D-110",
    category: "Plumbing",
    description: "Bathroom drain is blocked and water is stagnant.",
    dateRaised: "2025-09-22",
    assignedStaff: "Ramesh Kumar",
    status: "Pending",
    notes: "",
  },
  {
    id: 5,
    studentName: "Vikram Patel",
    room: "B-210",
    category: "Electricity",
    description: "Fan is making noise and not rotating properly.",
    dateRaised: "2025-09-18",
    assignedStaff: "Unassigned",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 6,
    studentName: "Neha Reddy",
    room: "A-105",
    category: "Other",
    description: "Window lock is broken, cannot secure the room properly.",
    dateRaised: "2025-09-21",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 7,
    studentName: "Aditya Kumar",
    room: "C-303",
    category: "Cleaning",
    description: "Garbage not collected from the floor, foul smell present.",
    dateRaised: "2025-09-20",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 8,
    studentName: "Isha Sharma",
    room: "D-115",
    category: "Plumbing",
    description:
      "Water pipe leaking in the kitchen area, needs immediate attention.",
    dateRaised: "2025-09-23",
    assignedStaff: "Ramesh Kumar",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 9,
    studentName: "Karan Joshi",
    room: "B-220",
    category: "Electricity",
    description: "Power socket not working, cannot plug in laptop.",
    dateRaised: "2025-09-19",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 10,
    studentName: "Sneha Kapoor",
    room: "A-110",
    category: "Other",
    description: "Mosquito net is torn and needs replacement.",
    dateRaised: "2025-09-22",
    assignedStaff: "Sunita Joshi",
    status: "Resolved",
    notes: "Net replaced on 2025-09-23",
  },
  // Additional 30 complaints
  {
    id: 11,
    studentName: "Rohan Mehra",
    room: "C-101",
    category: "Plumbing",
    description: "Sink tap leaking and causing puddles.",
    dateRaised: "2025-09-24",
    assignedStaff: "Ramesh Kumar",
    status: "Pending",
    notes: "",
  },
  {
    id: 12,
    studentName: "Ananya Reddy",
    room: "D-102",
    category: "Electricity",
    description: "Ceiling fan not working properly.",
    dateRaised: "2025-09-23",
    assignedStaff: "Unassigned",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 13,
    studentName: "Kabir Singh",
    room: "B-111",
    category: "Cleaning",
    description: "Floor not swept for the last two days.",
    dateRaised: "2025-09-20",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 14,
    studentName: "Meera Iyer",
    room: "A-115",
    category: "Plumbing",
    description: "Shower head is leaking constantly.",
    dateRaised: "2025-09-22",
    assignedStaff: "Ramesh Kumar",
    status: "Pending",
    notes: "",
  },
  {
    id: 15,
    studentName: "Advik Kumar",
    room: "C-120",
    category: "Other",
    description: "Door handle is broken, cannot close properly.",
    dateRaised: "2025-09-21",
    assignedStaff: "Sunita Joshi",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 16,
    studentName: "Tanya Mehta",
    room: "B-123",
    category: "Electricity",
    description: "Light flickers frequently in the room.",
    dateRaised: "2025-09-19",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 17,
    studentName: "Aryan Gupta",
    room: "A-130",
    category: "Cleaning",
    description: "Garbage bin overflowing.",
    dateRaised: "2025-09-18",
    assignedStaff: "Sunita Joshi",
    status: "Resolved",
    notes: "Bin emptied on 2025-09-19",
  },
  {
    id: 18,
    studentName: "Sakshi Jain",
    room: "D-135",
    category: "Plumbing",
    description: "Bathroom tap dripping continuously.",
    dateRaised: "2025-09-21",
    assignedStaff: "Ramesh Kumar",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 19,
    studentName: "Vihan Nair",
    room: "C-140",
    category: "Electricity",
    description: "Switchboard sparks when switched on.",
    dateRaised: "2025-09-22",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 20,
    studentName: "Anika Bhatia",
    room: "B-145",
    category: "Other",
    description: "Curtain rod broken, curtains falling.",
    dateRaised: "2025-09-23",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 21,
    studentName: "Devansh Kapoor",
    room: "A-150",
    category: "Cleaning",
    description: "Room floor sticky and unclean.",
    dateRaised: "2025-09-24",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 22,
    studentName: "Isha Reddy",
    room: "D-155",
    category: "Plumbing",
    description: "Leaking bathroom pipe.",
    dateRaised: "2025-09-22",
    assignedStaff: "Ramesh Kumar",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 23,
    studentName: "Kunal Sharma",
    room: "C-160",
    category: "Electricity",
    description: "Table lamp not working.",
    dateRaised: "2025-09-21",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 24,
    studentName: "Riya Verma",
    room: "B-165",
    category: "Other",
    description: "Broken wardrobe handle.",
    dateRaised: "2025-09-20",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 25,
    studentName: "Arjun Mishra",
    room: "A-170",
    category: "Cleaning",
    description: "Bathroom not cleaned properly.",
    dateRaised: "2025-09-19",
    assignedStaff: "Sunita Joshi",
    status: "Resolved",
    notes: "Cleaning done on 2025-09-20",
  },
  {
    id: 26,
    studentName: "Neha Jain",
    room: "D-175",
    category: "Plumbing",
    description: "Tap water pressure is low.",
    dateRaised: "2025-09-22",
    assignedStaff: "Ramesh Kumar",
    status: "Pending",
    notes: "",
  },
  {
    id: 27,
    studentName: "Ritvik Nair",
    room: "C-180",
    category: "Electricity",
    description: "Fan blades loose, making noise.",
    dateRaised: "2025-09-23",
    assignedStaff: "Unassigned",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 28,
    studentName: "Anshika Mehta",
    room: "B-185",
    category: "Other",
    description: "Door stopper missing, door hits wall.",
    dateRaised: "2025-09-24",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 29,
    studentName: "Kabir Reddy",
    room: "A-190",
    category: "Cleaning",
    description: "Dust on windows not cleaned.",
    dateRaised: "2025-09-20",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 30,
    studentName: "Tanya Sharma",
    room: "D-195",
    category: "Plumbing",
    description: "Bathroom drain is slow, water accumulates.",
    dateRaised: "2025-09-21",
    assignedStaff: "Ramesh Kumar",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 31,
    studentName: "Vivaan Kapoor",
    room: "C-200",
    category: "Electricity",
    description: "Light switch faulty, needs replacement.",
    dateRaised: "2025-09-22",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 32,
    studentName: "Meera Reddy",
    room: "B-205",
    category: "Other",
    description: "Broken shelf in study table.",
    dateRaised: "2025-09-23",
    assignedStaff: "Sunita Joshi",
    status: "Pending",
    notes: "",
  },
  {
    id: 33,
    studentName: "Aditya Verma",
    room: "A-210",
    category: "Cleaning",
    description: "Trash bin overflowing in room.",
    dateRaised: "2025-09-24",
    assignedStaff: "Sunita Joshi",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 34,
    studentName: "Isha Bhatia",
    room: "D-215",
    category: "Plumbing",
    description: "Bathroom pipe leaking slightly.",
    dateRaised: "2025-09-22",
    assignedStaff: "Ramesh Kumar",
    status: "Pending",
    notes: "",
  },
  {
    id: 35,
    studentName: "Rohan Nair",
    room: "C-220",
    category: "Electricity",
    description: "Power socket damaged, cannot charge devices.",
    dateRaised: "2025-09-23",
    assignedStaff: "Unassigned",
    status: "Pending",
    notes: "",
  },
  {
    id: 36,
    studentName: "Ananya Sharma",
    room: "B-225",
    category: "Other",
    description: "Window handle broken, cannot close properly.",
    dateRaised: "2025-09-24",
    assignedStaff: "Sunita Joshi",
    status: "In-Progress",
    notes: "",
  },
  {
    id: 37,
    studentName: "Vikram Gupta",
    room: "A-230",
    category: "Cleaning",
    description: "Bathroom floor slippery, not cleaned well.",
    dateRaised: "2025-09-20",
    assignedStaff: "Sunita Joshi",
    status: "Resolved",
    notes: "Cleaning completed on 2025-09-21",
  }
]


interface ExitRequest {
  studentName: string;
  enrollment: string;
  hostel: string;
  room: string;
  bed: string;
  exitDate: string;
  roomDues: number;
  fine: number;
  otherDues: number;
  totalDues: number;
  status: "Pending" | "Approved" | "Rejected";
}

export const exitTableData: ExitRequest[] = [
  {
    studentName: "Amit Sharma",
    enrollment: "ENR001",
    hostel: "Arya Hostel",
    room: "101",
    bed: "A1",
    exitDate: "2025-09-30",
    roomDues: 2000,
    fine: 500,
    otherDues: 0,
    totalDues: 2500,
    status: "Pending",
  },
  {
    studentName: "Neha Gupta",
    enrollment: "ENR002",
    hostel: "Bharat Hostel",
    room: "202",
    bed: "B2",
    exitDate: "2025-09-28",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Rohan Verma",
    enrollment: "ENR003",
    hostel: "Chandra Hostel",
    room: "303",
    bed: "C1",
    exitDate: "2025-10-01",
    roomDues: 500,
    fine: 0,
    otherDues: 100,
    totalDues: 600,
    status: "Pending",
  },
  {
    studentName: "Priya Sharma",
    enrollment: "ENR004",
    hostel: "Arya Hostel",
    room: "102",
    bed: "A2",
    exitDate: "2025-10-02",
    roomDues: 1000,
    fine: 200,
    otherDues: 50,
    totalDues: 1250,
    status: "Pending",
  },
  {
    studentName: "Aditya Kumar",
    enrollment: "ENR005",
    hostel: "Bharat Hostel",
    room: "203",
    bed: "B1",
    exitDate: "2025-10-03",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Sakshi Verma",
    enrollment: "ENR006",
    hostel: "Chandra Hostel",
    room: "304",
    bed: "C2",
    exitDate: "2025-10-04",
    roomDues: 300,
    fine: 0,
    otherDues: 50,
    totalDues: 350,
    status: "Pending",
  },
  {
    studentName: "Vikram Singh",
    enrollment: "ENR007",
    hostel: "Arya Hostel",
    room: "103",
    bed: "A1",
    exitDate: "2025-10-05",
    roomDues: 800,
    fine: 100,
    otherDues: 0,
    totalDues: 900,
    status: "Pending",
  },
  {
    studentName: "Ananya Reddy",
    enrollment: "ENR008",
    hostel: "Bharat Hostel",
    room: "204",
    bed: "B2",
    exitDate: "2025-10-06",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Devansh Mehta",
    enrollment: "ENR009",
    hostel: "Chandra Hostel",
    room: "305",
    bed: "C1",
    exitDate: "2025-10-07",
    roomDues: 600,
    fine: 50,
    otherDues: 0,
    totalDues: 650,
    status: "Pending",
  },
  {
    studentName: "Isha Kapoor",
    enrollment: "ENR010",
    hostel: "Arya Hostel",
    room: "104",
    bed: "A2",
    exitDate: "2025-10-08",
    roomDues: 400,
    fine: 0,
    otherDues: 100,
    totalDues: 500,
    status: "Pending",
  },
  {
    studentName: "Kabir Nair",
    enrollment: "ENR011",
    hostel: "Bharat Hostel",
    room: "205",
    bed: "B1",
    exitDate: "2025-10-09",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Anika Bhatia",
    enrollment: "ENR012",
    hostel: "Chandra Hostel",
    room: "306",
    bed: "C2",
    exitDate: "2025-10-10",
    roomDues: 700,
    fine: 150,
    otherDues: 50,
    totalDues: 900,
    status: "Pending",
  },
  {
    studentName: "Ritvik Sharma",
    enrollment: "ENR013",
    hostel: "Arya Hostel",
    room: "105",
    bed: "A1",
    exitDate: "2025-10-11",
    roomDues: 1000,
    fine: 0,
    otherDues: 0,
    totalDues: 1000,
    status: "Pending",
  },
  {
    studentName: "Sanya Joshi",
    enrollment: "ENR014",
    hostel: "Bharat Hostel",
    room: "206",
    bed: "B2",
    exitDate: "2025-10-12",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Aarav Gupta",
    enrollment: "ENR015",
    hostel: "Chandra Hostel",
    room: "307",
    bed: "C1",
    exitDate: "2025-10-13",
    roomDues: 500,
    fine: 0,
    otherDues: 0,
    totalDues: 500,
    status: "Pending",
  },
  {
    studentName: "Meera Singh",
    enrollment: "ENR016",
    hostel: "Arya Hostel",
    room: "106",
    bed: "A2",
    exitDate: "2025-10-14",
    roomDues: 200,
    fine: 50,
    otherDues: 0,
    totalDues: 250,
    status: "Pending",
  },
  {
    studentName: "Aditya Reddy",
    enrollment: "ENR017",
    hostel: "Bharat Hostel",
    room: "207",
    bed: "B1",
    exitDate: "2025-10-15",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Tanya Kapoor",
    enrollment: "ENR018",
    hostel: "Chandra Hostel",
    room: "308",
    bed: "C2",
    exitDate: "2025-10-16",
    roomDues: 600,
    fine: 100,
    otherDues: 50,
    totalDues: 750,
    status: "Pending",
  },
  {
    studentName: "Kabir Mehta",
    enrollment: "ENR019",
    hostel: "Arya Hostel",
    room: "107",
    bed: "A1",
    exitDate: "2025-10-17",
    roomDues: 300,
    fine: 0,
    otherDues: 0,
    totalDues: 300,
    status: "Pending",
  },
  {
    studentName: "Ananya Sharma",
    enrollment: "ENR020",
    hostel: "Bharat Hostel",
    room: "208",
    bed: "B2",
    exitDate: "2025-10-18",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Rohan Nair",
    enrollment: "ENR021",
    hostel: "Chandra Hostel",
    room: "309",
    bed: "C1",
    exitDate: "2025-10-19",
    roomDues: 400,
    fine: 50,
    otherDues: 50,
    totalDues: 500,
    status: "Pending",
  },
  {
    studentName: "Neha Singh",
    enrollment: "ENR022",
    hostel: "Arya Hostel",
    room: "108",
    bed: "A2",
    exitDate: "2025-10-20",
    roomDues: 200,
    fine: 0,
    otherDues: 0,
    totalDues: 200,
    status: "Pending",
  },
  {
    studentName: "Aarav Joshi",
    enrollment: "ENR023",
    hostel: "Bharat Hostel",
    room: "209",
    bed: "B1",
    exitDate: "2025-10-21",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  },
  {
    studentName: "Isha Mehta",
    enrollment: "ENR024",
    hostel: "Chandra Hostel",
    room: "310",
    bed: "C2",
    exitDate: "2025-10-22",
    roomDues: 500,
    fine: 100,
    otherDues: 50,
    totalDues: 650,
    status: "Pending",
  },
  {
    studentName: "Vikram Sharma",
    enrollment: "ENR025",
    hostel: "Arya Hostel",
    room: "109",
    bed: "A1",
    exitDate: "2025-10-23",
    roomDues: 300,
    fine: 50,
    otherDues: 0,
    totalDues: 350,
    status: "Pending",
  },
  {
    studentName: "Sanya Gupta",
    enrollment: "ENR026",
    hostel: "Bharat Hostel",
    room: "210",
    bed: "B2",
    exitDate: "2025-10-24",
    roomDues: 0,
    fine: 0,
    otherDues: 0,
    totalDues: 0,
    status: "Approved",
  }
];

export type Hostel = {
  id: string;
  name: string;
  capacity: number;
  floors: number;
  warden: string;
  facilities: string;
};

export const hostelList: Hostel[] = [
  {
    id: "1",
    name: "Aryabhatta Hostel",
    capacity: 300,
    floors: 5,
    warden: "Mr. Sharma",
    facilities: "WiFi, Mess, Laundry",
  },
  {
    id: "2",
    name: "Gargi Hostel",
    capacity: 200,
    floors: 3,
    warden: "Ms. Verma",
    facilities: "WiFi, Mess",
  },
  {
    id: "3",
    name: "Vishveshwaraiya Hostel",
    capacity: 250,
    floors: 4,
    warden: "Mr. Reddy",
    facilities: "WiFi, Mess, Gym",
  },
  {
    id: "4",
    name: "Kalpana Chawla Hostel",
    capacity: 180,
    floors: 3,
    warden: "Ms. Iyer",
    facilities: "WiFi, Mess, Laundry",
  },
  {
    id: "5",
    name: "C.V. Raman Hostel",
    capacity: 220,
    floors: 4,
    warden: "Mr. Gupta",
    facilities: "WiFi, Mess, Sports Ground",
  },
  {
    id: "6",
    name: "Bhabha Hostel",
    capacity: 150,
    floors: 2,
    warden: "Ms. Singh",
    facilities: "WiFi, Mess",
  },
  {
    id: "7",
    name: "Raman Hostel",
    capacity: 200,
    floors: 3,
    warden: "Mr. Joshi",
    facilities: "WiFi, Mess, Laundry, Gym",
  },
];


export const hallTicketData = [
  {
    exam: "End Semester",
    startDate: "27/09/2025",
    endDate: "05/10/2025",
    semester: "II",
    subjects: ["Mathematics II", "Electronics", "Chemistry", "Computer Science"],
  },
  {
    exam: "Mid Semester",
    startDate: "01/03/2025",
    endDate: "05/03/2025",
    semester: "II",
    subjects: ["Mathematics II", "Electronics", "Chemistry"],
  },

  {
    exam: "End Semester",
    startDate: "20/07/2025",
    endDate: "30/07/2025",
    semester: "I",
    subjects: ["Mathematics", "Physics", "Chemistry", "Computer Science"],
  },
  {
    exam: "Mid Semester",
    startDate: "01/05/2025",
    endDate: "05/05/2025",
    semester: "I",
    subjects: ["Mathematics", "Physics", "Chemistry"],
  },
];


export const examTimetableData = [
  // Semester II - End Semester
  {
    semester: 2,
    exam: "End Semester",
    subject: "Mathematics II",
    date: "27/09/2025",
    time: "10:00 AM",
    venue: "Hall 201",
    status: "Ongoing",
  },
  {
    semester: 2,
    exam: "End Semester",
    subject: "Electronics",
    date: "28/09/2025",
    time: "2:00 PM",
    venue: "Hall 202",
    status: "Upcoming",
  },
  {
    semester: 2,
    exam: "End Semester",
    subject: "Chemistry",
    date: "29/09/2025",
    time: "10:00 AM",
    venue: "Hall 203",
    status: "Upcoming",
  },
  {
    semester: 2,
    exam: "End Semester",
    subject: "Computer Science",
    date: "30/09/2025",
    time: "2:00 PM",
    venue: "Hall 204",
    status: "Upcoming",
  },

  // Semester II - Mid Semester
  {
    semester: 2,
    exam: "Mid Semester",
    subject: "Mathematics II",
    date: "01/03/2025",
    time: "10:00 AM",
    venue: "Hall 205",
    status: "Past",
  },
  {
    semester: 2,
    exam: "Mid Semester",
    subject: "Electronics",
    date: "02/03/2025",
    time: "2:00 PM",
    venue: "Hall 206",
    status: "Past",
  },
  {
    semester: 2,
    exam: "Mid Semester",
    subject: "Chemistry",
    date: "03/03/2025",
    time: "10:00 AM",
    venue: "Hall 207",
    status: "Past",
  },

  // Semester I - End Semester
  {
    semester: 1,
    exam: "End Semester",
    subject: "Mathematics",
    date: "20/07/2025",
    time: "10:00 AM",
    venue: "Hall 101",
    status: "Past",
  },
  {
    semester: 1,
    exam: "End Semester",
    subject: "Physics",
    date: "21/07/2025",
    time: "2:00 PM",
    venue: "Hall 102",
    status: "Past",
  },
  {
    semester: 1,
    exam: "End Semester",
    subject: "Chemistry",
    date: "22/07/2025",
    time: "10:00 AM",
    venue: "Hall 103",
    status: "Past",
  },
  {
    semester: 1,
    exam: "End Semester",
    subject: "Computer Science",
    date: "23/07/2025",
    time: "2:00 PM",
    venue: "Hall 104",
    status: "Past",
  },

  // Semester I - Mid Semester
  {
    semester: 1,
    exam: "Mid Semester",
    subject: "Mathematics",
    date: "01/05/2025",
    time: "10:00 AM",
    venue: "Hall 105",
    status: "Past",
  },
  {
    semester: 1,
    exam: "Mid Semester",
    subject: "Physics",
    date: "02/05/2025",
    time: "2:00 PM",
    venue: "Hall 106",
    status: "Past",
  },
  {
    semester: 1,
    exam: "Mid Semester",
    subject: "Chemistry",
    date: "03/05/2025",
    time: "10:00 AM",
    venue: "Hall 107",
    status: "Past",
  },
];

export const attendanceData = [
  // Semester II - Mid Semester
  {
    semester: 2,
    exam: "Mid Semester",
    subject: "Mathematics II",
    date: "01/03/2025",
    status: "Present",
  },
  {
    semester: 2,
    exam: "Mid Semester",
    subject: "Electronics",
    date: "02/03/2025",
    status: "Absent",
  },
  {
    semester: 2,
    exam: "Mid Semester",
    subject: "Chemistry",
    date: "03/03/2025",
    status: "Present",
  },

  // Semester I - End Semester
  {
    semester: 1,
    exam: "End Semester",
    subject: "Mathematics",
    date: "20/07/2025",
    status: "Present",
  },
  {
    semester: 1,
    exam: "End Semester",
    subject: "Physics",
    date: "21/07/2025",
    status: "Absent",
  },
  {
    semester: 1,
    exam: "End Semester",
    subject: "Chemistry",
    date: "22/07/2025",
    status: "Present",
  },
  {
    semester: 1,
    exam: "End Semester",
    subject: "Computer Science",
    date: "23/07/2025",
    status: "Present",
  },

  // Semester I - Mid Semester
  {
    semester: 1,
    exam: "Mid Semester",
    subject: "Mathematics",
    date: "01/05/2025",
    status: "Present",
  },
  {
    semester: 1,
    exam: "Mid Semester",
    subject: "Physics",
    date: "02/05/2025",
    status: "Present",
  },
  {
    semester: 1,
    exam: "Mid Semester",
    subject: "Chemistry",
    date: "03/05/2025",
    status: "Absent",
  },
];


export const internalMarksData = [
  {
    subject: "Mathematics",
    assessment: "Assignment 1",
    marks: 18,
    total: 20,
    grade: "A",
  },
  {
    subject: "Physics",
    assessment: "Mid-term",
    marks: 45,
    total: 50,
    grade: "A+",
  },
];

export const revaluationData = [
  { exam: "Semester", subject: "Mathematics", marks: 78, status: "Pending" },
  { exam: "Semester", subject: "Physics", marks: 62, status: "Applied" },
];

export const semesterResultsData = [
  {
    semester: 1,
    sno: 1,
    session: "2024-25",
    section: "A",
    registeredCourses: 10,
    registeredCredits: 40,
    earnedCredits: 38,
    sgpa: 8.2,
    cgpa: 8.2,
    resultDate: "05/08/2025",
  },
  {
    semester: 2,
    sno: 2,
    session: "2024-25",
    section: "A",
    registeredCourses: 10,
    registeredCredits: 42,
    earnedCredits: 41,
    sgpa: 8.5,
    cgpa: 8.35,
    resultDate: "10/12/2025",
  }
];

export const subjectResultsData = [
  // Semester 1
  { semester: 1, courseName: "Mathematics I", examType: "End Semester", courseType: "Core", credits: 4, grade: "A", gradePoint: 9, earnedGradePoints: 36, result: "Pass" },
  { semester: 1, courseName: "Physics I", examType: "End Semester", courseType: "Core", credits: 4, grade: "B+", gradePoint: 8, earnedGradePoints: 32, result: "Pass" },
  { semester: 1, courseName: "Chemistry I", examType: "End Semester", courseType: "Core", credits: 4, grade: "A", gradePoint: 9, earnedGradePoints: 36, result: "Pass" },
  { semester: 1, courseName: "Computer Science I", examType: "End Semester", courseType: "Core", credits: 4, grade: "A+", gradePoint: 10, earnedGradePoints: 40, result: "Pass" },
  { semester: 1, courseName: "English", examType: "End Semester", courseType: "Elective", credits: 3, grade: "B", gradePoint: 7, earnedGradePoints: 21, result: "Pass" },
  { semester: 1, courseName: "Environmental Science", examType: "Mid Semester", courseType: "Core", credits: 3, grade: "A", gradePoint: 9, earnedGradePoints: 27, result: "Pass" },
  { semester: 1, courseName: "Biology", examType: "End Semester", courseType: "Core", credits: 4, grade: "B+", gradePoint: 8, earnedGradePoints: 32, result: "Pass" },
  { semester: 1, courseName: "Engineering Mechanics", examType: "Mid Semester", courseType: "Core", credits: 3, grade: "A", gradePoint: 9, earnedGradePoints: 27, result: "Pass" },
  { semester: 1, courseName: "Electrical Basics", examType: "End Semester", courseType: "Core", credits: 3, grade: "B", gradePoint: 7, earnedGradePoints: 21, result: "Pass" },
  { semester: 1, courseName: "Physical Education", examType: "End Semester", courseType: "Elective", credits: 2, grade: "A+", gradePoint: 10, earnedGradePoints: 20, result: "Pass" },

  // Semester 2 (different subjects)
  { semester: 2, courseName: "Mathematics II", examType: "End Semester", courseType: "Core", credits: 4, grade: "A+", gradePoint: 10, earnedGradePoints: 40, result: "Pass" },
  { semester: 2, courseName: "Physics II", examType: "End Semester", courseType: "Core", credits: 4, grade: "A", gradePoint: 9, earnedGradePoints: 36, result: "Pass" },
  { semester: 2, courseName: "Chemistry II", examType: "End Semester", courseType: "Core", credits: 4, grade: "B+", gradePoint: 8, earnedGradePoints: 32, result: "Pass" },
  { semester: 2, courseName: "Computer Science II", examType: "End Semester", courseType: "Core", credits: 4, grade: "A", gradePoint: 9, earnedGradePoints: 36, result: "Pass" },
  { semester: 2, courseName: "English II", examType: "End Semester", courseType: "Elective", credits: 3, grade: "B+", gradePoint: 8, earnedGradePoints: 24, result: "Pass" },
  { semester: 2, courseName: "Electronics", examType: "Mid Semester", courseType: "Core", credits: 3, grade: "A", gradePoint: 9, earnedGradePoints: 27, result: "Pass" },
  { semester: 2, courseName: "Mechanics II", examType: "End Semester", courseType: "Core", credits: 4, grade: "B+", gradePoint: 8, earnedGradePoints: 32, result: "Pass" },
  { semester: 2, courseName: "Electrical Circuits", examType: "Mid Semester", courseType: "Core", credits: 3, grade: "A", gradePoint: 9, earnedGradePoints: 27, result: "Pass" },
  { semester: 2, courseName: "Biology II", examType: "End Semester", courseType: "Core", credits: 3, grade: "B", gradePoint: 7, earnedGradePoints: 21, result: "Pass" },
  { semester: 2, courseName: "Environmental Studies", examType: "End Semester", courseType: "Elective", credits: 2, grade: "A+", gradePoint: 10, earnedGradePoints: 20, result: "Pass" },
];


export const catalogueData = [
  { id: 1, title: "Digital Electronics", author: "R. Boylestad", type: "Book", subject: "Electronics", availability: "Available" },
  { id: 2, title: "AI Journal 2025", author: "Various", type: "Journal", subject: "Computer Science", availability: "Issued" },
  { id: 3, title: "Advanced Physics", author: "Halliday", type: "Book", subject: "Physics", availability: "Available" },
  { id: 4, title: "Data Structures", author: "S. Lipschutz", type: "Book", subject: "Computer Science", availability: "Available" },
  { id: 5, title: "Power Electronics", author: "M. Rashid", type: "Book", subject: "Electronics", availability: "Issued" },
  { id: 6, title: "Modern Chemistry", author: "Zumdahl", type: "Book", subject: "Chemistry", availability: "Available" },
  { id: 7, title: "Quantum Mechanics", author: "Griffiths", type: "Book", subject: "Physics", availability: "Available" },
  { id: 8, title: "Computer Networks Journal", author: "Various", type: "Journal", subject: "Computer Science", availability: "Available" },
  { id: 9, title: "Embedded Systems", author: "Raj Kamal", type: "Book", subject: "Electronics", availability: "Issued" },
];

export const currentIssuesData = [
  { id: 1, title: "Mathematics II", author: "J. Stewart", borrowDate: "01/09/2025", dueDate: "15/09/2025", status: "Overdue" },
  { id: 2, title: "Physics Concepts", author: "Halliday", borrowDate: "05/09/2025", dueDate: "20/09/2025", status: "On Time" },
  { id: 3, title: "Data Structures", author: "S. Lipschutz", borrowDate: "10/09/2025", dueDate: "25/09/2025", status: "On Time" },
  { id: 4, title: "Power Electronics", author: "M. Rashid", borrowDate: "12/09/2025", dueDate: "27/09/2025", status: "On Time" },
];

export const historyData = [
  { id: 1, title: "Chemistry I", author: "Brown", borrowDate: "01/03/2025", returnDate: "15/03/2025" },
  { id: 2, title: "Mathematics I", author: "J. Stewart", borrowDate: "15/04/2025", returnDate: "30/04/2025" },
  { id: 3, title: "Physics I", author: "Halliday", borrowDate: "01/05/2025", returnDate: "15/05/2025" },
  { id: 4, title: "Digital Electronics", author: "R. Boylestad", borrowDate: "10/06/2025", returnDate: "25/06/2025" },
];

export const finesData = [
  { id: 1, title: "Mathematics II", dueDate: "15/09/2025", fineAmount: 50, paymentStatus: "Unpaid" },
  { id: 2, title: "Physics Concepts", dueDate: "20/09/2025", fineAmount: 0, paymentStatus: "Paid" },
  { id: 3, title: "Power Electronics", dueDate: "27/09/2025", fineAmount: 20, paymentStatus: "Unpaid" },
  { id: 4, title: "Data Structures", dueDate: "25/09/2025", fineAmount: 0, paymentStatus: "Paid" },
];

export const digitalLibraryData = [
  { id: 1, title: "AI Fundamentals", author: "Stuart Russell", type: "eBook" },
  { id: 2, title: "Machine Learning Guide", author: "Andrew Ng", type: "PDF" },
  { id: 3, title: "Digital Circuits", author: "R. Boylestad", type: "eBook" },
  { id: 4, title: "Embedded Systems Handbook", author: "Raj Kamal", type: "PDF" },
  { id: 5, title: "Quantum Physics for Beginners", author: "Griffiths", type: "eBook" },
  { id: 6, title: "Computer Networks Handbook", author: "Tanenbaum", type: "PDF" },
];

export const subjects = ["All", "Electronics", "Computer Science", "Physics", "Chemistry", "Mathematics"];
export const types = ["All", "Book", "Journal", "eBook", "PDF"];

// Hostels Data
// export const hostelsData = [
//   {
//     id: 1,
//     name: "Sunrise Hostel",
//     floorCount: 3,
//     rooms: [
//       { roomNo: "101", type: "Single", occupancy: 1, capacity: 1 },
//       { roomNo: "102", type: "Double", occupancy: 1, capacity: 2 },
//       { roomNo: "103", type: "Double", occupancy: 2, capacity: 2 },
//     ],
//     images: [
//       "/images/hostel1-1.jpg",
//       "/images/hostel1-2.jpg",
//       "/images/hostel1-3.jpg",
//     ],
//     facilities: ["Mess", "WiFi", "Laundry", "Gym"],
//     fees: [
//       { semester: "Fall 2025", amount: 15000, status: "Paid" },
//       { semester: "Spring 2026", amount: 15000, status: "Unpaid" },
//     ],
//   },
//   {
//     id: 2,
//     name: "Green Valley Hostel",
//     floorCount: 2,
//     rooms: [
//       { roomNo: "201", type: "Single", occupancy: 0, capacity: 1 },
//       { roomNo: "202", type: "Double", occupancy: 1, capacity: 2 },
//       { roomNo: "203", type: "Double", occupancy: 2, capacity: 2 },
//     ],
//     images: [
//       "/images/hostel2-1.jpg",
//       "/images/hostel2-2.jpg",
//       "/images/hostel2-3.jpg",
//     ],
//     facilities: ["Mess", "WiFi", "Library"],
//     fees: [
//       { semester: "Fall 2025", amount: 16000, status: "Unpaid" },
//       { semester: "Spring 2026", amount: 16000, status: "Pending" },
//     ],
//   },
//   {
//     id: 3,
//     name: "River View Hostel",
//     floorCount: 3,
//     rooms: [
//       { roomNo: "301", type: "Single", occupancy: 0, capacity: 1 },
//       { roomNo: "302", type: "Double", occupancy: 1, capacity: 2 },
//     ],
//     images: [
//       "/images/hostel3-1.jpg",
//       "/images/hostel3-2.jpg",
//       "/images/hostel3-3.jpg",
//     ],
//     facilities: ["WiFi", "Gym", "CCTV"],
//     fees: [
//       { semester: "Fall 2025", amount: 17000, status: "Paid" },
//       { semester: "Spring 2026", amount: 17000, status: "Paid" },
//     ],
//   },
// ];
// Hostels Data
export const hostelsData = [
  {
    id: 1,
    name: "Sunrise Hostel",
    gender: "Boys",
    floorCount: 3,
    rooms: [
      { roomNo: "101", type: "Single", occupancy: 1, capacity: 1 },
      { roomNo: "102", type: "Double", occupancy: 1, capacity: 2 },
      { roomNo: "103", type: "Double", occupancy: 2, capacity: 2 },
    ],
    images: [
      "/images/hostel1-1.jpg",
      "/images/hostel1-2.jpg",
      "/images/hostel1-3.jpg",
    ],
    facilities: ["Mess", "WiFi", "Laundry", "Gym"],
    fees: [
      { semester: "Fall 2025", amount: 15000, status: "Paid" },
      { semester: "Spring 2026", amount: 15000, status: "Unpaid" },
    ],
  },
  {
    id: 2,
    name: "Green Valley Hostel",
    gender: "Girls",
    floorCount: 2,
    rooms: [
      { roomNo: "201", type: "Single", occupancy: 0, capacity: 1 },
      { roomNo: "202", type: "Double", occupancy: 1, capacity: 2 },
      { roomNo: "203", type: "Double", occupancy: 2, capacity: 2 },
    ],
    images: [
      "/images/hostel1-1.jpg",
      "/images/hostel1-2.jpg",
      "/images/hostel1-3.jpg",
    ],
    facilities: ["Mess", "WiFi", "Library"],
    fees: [
      { semester: "Fall 2025", amount: 16000, status: "Unpaid" },
      { semester: "Spring 2026", amount: 16000, status: "Pending" },
    ],
  },
  {
    id: 3,
    name: "River View Hostel",
    gender: "Boys",
    floorCount: 3,
    rooms: [
      { roomNo: "301", type: "Single", occupancy: 0, capacity: 1 },
      { roomNo: "302", type: "Double", occupancy: 1, capacity: 2 },
    ],
    images: [
      "/images/hostel1-1.jpg",
      "/images/hostel1-2.jpg",
      "/images/hostel1-3.jpg",
    ],
    facilities: ["WiFi", "Gym", "CCTV"],
    fees: [
      { semester: "Fall 2025", amount: 17000, status: "Paid" },
      { semester: "Spring 2026", amount: 17000, status: "Paid" },
    ],
  },
];



// Hostel Fees
export const hostelFeesData = [
  { id: 1, semester: "Fall 2025", amount: 15000, status: "Paid" },
  { id: 2, semester: "Spring 2026", amount: 15000, status: "Unpaid" },
  { id: 3, semester: "Fall 2026", amount: 16000, status: "Unpaid" },
  { id: 4, semester: "Spring 2027", amount: 16000, status: "Pending" },
  { id: 5, semester: "Fall 2027", amount: 17000, status: "Paid" },
];

// Complaints
export const complaintsData = [
  { id: 1, type: "Mess", description: "Food quality issue", status: "Pending" },
  { id: 2, type: "Maintenance", description: "Leaky faucet", status: "Resolved" },
  { id: 3, type: "Mess", description: "Delayed breakfast", status: "Resolved" },
  { id: 4, type: "Maintenance", description: "Air conditioner not working", status: "Pending" },
  { id: 5, type: "Roommate", description: "Noise issue in room 203", status: "Pending" },
  { id: 6, type: "Mess", description: "Vegetarian options not sufficient", status: "Pending" },
];
